language:
- scala
dist:
- trusty
jdk:
- oraclejdk8
scala:
- 2.12.8
branches: 
only:
- master
before_install:
- nvm install 6
- node --version
- npm --version
install:
- npm install -g serverless
script:
- sbt assembly
after_script:
- serverless deploy -v
env:
  global:
  - secure: mDwcBUlfNLna94lzli9O9t7OtmYwaEsA0BNlWIo96HQoUXhXDV0qVw15cQ1QAYl+ekXnyuATy/bkXliZvVhZOGOhpMnlgvxuvR/9/kXEXGc5C5mzcBfajSAY2jVg995CYlQ1y1X/NCfiWSwXya6IM4K4Zff0YHBJPWzAp2jOzImsOuxZ45IsAzGTLx8sfj27QKU6OUc574QxkSzZFTEyx8ErDPL+RkhLhUf2U+LsIeW1816/L05zpRoOv8UqqK/Oz4B3yktIs6r+BQqJmn5AxjzY/oV7BU7sSi5wwNFyMTwfHqqY83vbSJPEVKfMo+QyB0W/9c9/+nYxi5GV8Wf9yO2zvKEBWIvxGlrlkIEM56A6g7TXWt+b9mINrAU/mI5yA8hjSi3X2Gpc5XR7s6BuEtUw6pjnv2Wis89JAPhQdOz6hbyEyJB/gqvHlZguUh6N5QyCtNCPjtmXE3I7u4B43PFKFgHFxOaBV3TQ1Y9XQjG467UyhdvXwvRxkGFgL7pE9vYqK349dMRHK3whU12puSWglWEaSV4wuNlGniIn0qLebNoaPMF4Y/DPp7IeYEDxChPPw417xtv3IiWY4wASTHaBbj/kzFKv4vjnDNh0rpEzJpgTpvkFKdAoXG5AUt7iRVGxzWP4sLhPh34dvcfKePWRl95foQZzPFOg7JAZAFE=
  - secure: iS2EhVZamlrTJisQCCiDQwzeb7vDVY7X6rP3WtZsVxNegte0M3JLFsldDxuwT9UT4/Sa9Lo08qWGJi8PRz9dUIKIQ3Rk+mEqm/i8alo04/jY091yADsRgmiM0RPoFKDHCUTOzk+5vxcVRF2Mym1jOYUz/K8CEohYiNirpr+EW8JcNfoigNskrTtH65kUL4KDvv+a8P6QQXyOemWDCvhJsMNrVgX1yD5EQ5eLRDqd/HipYZqfEKbxk+BZcwk2rW7Haa1N8cSa/sHmKZn6ic1M6kD5D3mykGH9qr2s5Un93cMUmCz5lVQmOxHqa2r+n2WVxXPF0uue/AjqXs6N6fwL966yasNvRDCPk2acIAo6smNXcFrzj6MxX5E21yQlGhp4IqS6jNd2P2YFNnl6eAC3QqFOsUAcKtdgeQF6g+CliG3gRQsvOrVplQHPBdStOjKAxmDbeKwS5YstWx7Q0evEftuR/wA9d8kNC3K9kHTLn3MesKFCYUK6w5Mw0L3kSH9/jqbIpt9SHRjvzXLigl69bpVPC6Cnp6pFsQkyH+ObFeT57S8dQlAbv1jpS/VR6zw/txrrMl4aEvZUnyMCAkcgpxQAFoPiguGjmhMnj/VZ+abetpWwQGN6gQHJ4VY8naWd97JBtIEC1XFuEJUxs5THC3sMjdpbTXNc37fuWRrKqXc=
