language:
- scala
jdk:
- oraclejdk8
scala:
- 2.12.8
branches: 
only:
- master
before_install:
- nvm install 6
- node --version
- npm --version
install:
- npm install -g serverless
script:
- sbt assembly
after_script:
- serverless deploy -v
env:
  global:
  - secure: DuFcPuQFs7i9LPdIiNKVdBRgHHG0A2cN9tSmrugxSlPBSs1MO2Oi3jx+ji8D2SrSwc7OPQoJfbbT8NbsbWm6J7AJa4LjAku2bwH2MDRUeWQDBtvnTOvAYgEXOQYYXnuArSrmfqbGc8+Etyu9jwmvafZGSTXJFOLi6PWLcieA9H7oyY6d+L56zIe4H2oBjzY39KL9YaMDXDnZv67+3Zjnyr3v39Y0ZIK2K3/i1tuGw7nMC5TIwi0vpSX87cRqGulNlCXWDsE4r5sGdR4oekLJb4/S6VolppipCEZW8whhM5YnT1F4YU2rID2EiEFfSSaV7zRdG13g2mWpGIo6PgEzksXWuAyzR39hZTOIxjELEFtkvyIH674HuU3xHKTuAkuMKZBwVdj/GMlW18KGK4t3tL1uOTw6hXmcKOxy6krOUIuRLo8iCC9+OKW5EPE+WlxqbDLgMNSJdjHSVhspYeQc5zgmFARXMGGqJ3nKBj8kfrw4t0NJi/1EKHnSjqlUyz5ezTlD3gOA4DKNLl6yNCl8xVM3viWR1R03E0D12WNlc/S5VnKXVLJFKRai4oWim+nWcyw8b8aICHSbm7LlVDQyQ4LxxymFLF+Ev9cTsFt69xosw+uden+NQEqcRGUbWvhK3mNg6y9K84Ab5ZdlDFI7jUxOd4KSGyF0jrV0RfWQ63U=
  - secure: gJa0CxtbxyY+9wVR/Z9gXJ6rMmPkbpitnkhNlsdAiBLkZgHcgVT7UexJsHUKxpBxvJxAywnWJs6Ytsvkq3/hMBGs5P1q55OhNYH0wgrocI5nIKaxYpPXwJbeW/e3IyP7DgcSVIHDOzzRZHkOKLQdCvKEGUTFoDPPMg5h+Tp90GqfJCPd5x40dYfdaXRS1W/xIZkW7MkZf7dXs9FJ36aINTLhWVRaZZsMKpK/PC+okWFVrsf4GNL6f5fjDkP/jH15FyjKgnHOL/Qwv5UaZRfvMuh0S/ntfdxUPv6PTvu4uDb8zJd1b5vd9znEWQu5NXScNnF/hgaGuidtF1PuYw3rM9b/yDHJrEEXT0s9h5fEAiPiNO/+E2BDngiTXfs4YXnVSugDeEEpIPAUKuuscs5g8KKEYHyFONMHG3aesz5vRe4wPlRlXezWtICL3bBT4SvYtCftZ5VIzpCetoWzEPyjYg8dP1OVpf1aETW0l+oK+daVsNSQtZ6bwSE/0+/7lSFl/v9BdbjHnEEqKr0JIZjiOTjpy5kbKpuNgAINUtgD3vyR6crwHxMZvlStWXENGdSj47cte2pPtXLItQHyVcYghCAsrXZAJpZ4D+by998YVqZaWsalZtUM2pKD1v8JKQM0FHyZIH/G2JD+uVWiAieM+m02+OR0ELfE1qrpdWWmq18=
